name: Terraform and Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Package distributor Lambda
        run: |
          cd lambdas/distributor
          zip -r ../../lambdas/distributor.zip .
          
      - name: Package processor Lambda
        run: |
          cd lambdas/processor
          zip -r ../../lambdas/processor.zip .

      - name: Upload Lambda packages to S3
        run: |
          aws s3 cp lambdas/distributor.zip s3://lambda-codes-tf/distributor.zip
          aws s3 cp lambdas/processor.zip s3://lambda-codes-tf/processor.zip

      - name: Trigger Terraform Apply again to update Lambda code
        run: terraform apply -auto-approve
